### ISSUE TITLE
Problems when trying to do cmake -DCMAKE_INSTALL_PREFIX=<your_GNURadio_install_dir> ../

### ISSUE THREAD

**Issue by calgab93** [git-artes/gr-isdbt#12]
Hello!
I am new here, and I am trying to install this code for my personal use.
I have issues when trying to do cmake -DCMAKE_INSTALL_PREFIX=<your_GNURadio_install_dir> ../ after running all those steps and it says: bash: ../: Is a directory
Can you please help me to get over this step ?
My gnuradio install is: /home/myname/src/gnuradio (Installed with pyBombs).

Thanks in advance!

**Comment by vagonbar** [comment]
Please see installation notes in README.md, main page of gr-isdbt project,
    https://github.com/git-artes/gr-isdbt
where it says "For a user space installation...".
  PyBombs installs in a user directory, you must indicate it in the cmake
statement.
  Hope this helps.


2016-04-09 5:55 GMT-03:00 calgab93 <notifications@github.com>:

> Hello!
> I am new here, and I am trying to install this code for my personal use.
> I have issues when trying to do cmake -DCMAKE_INSTALL_PREFIX= ../ after
> running all those steps and it says: bash: ../: Is a directory
> Can you please help me to get over this step ?
> My gnuradio install is: /home/myname/src/gnuradio (Installed with pyBombs).
>
> Thanks in advance!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/git-artes/gr-isdbt/issues/12>
>



-- 
Victor Gonzalez Barbone
E-mail: vagonbar en fing edu uy, vagonbar en gmail com
Instituto de Ingenieria Electrica. Fac.de Ingenieria
http://iie.fing.edu.uy/~vagonbar
