### ISSUE TITLE
DTV recording and TMCC displaying

### ISSUE THREAD

**Issue by eaiglesiasr** [git-artes/gr-isdbt#14]
Hi! I'd like to comment the following: I've been trying to record a TV RF signal from DTV local channel, using a USRP N200 and daughter TVRX2 card, in order to obtain its TMCC parameters through   "obtaining_parameters.grc" , but any successful parameter was received ( I attached three images)..so that I have the following questions: is it ok the way of recording of RF DTV signal o there's another way? is there any problem or special issue  in the received spectrum?  I will be  thanked if someone help me...

![screenshot from 2016-05-30 19 34 46](https://cloud.githubusercontent.com/assets/15164994/15657132/ab5ebe5e-269d-11e6-9948-5b3316d995c8.png)
   
![screenshot from 2016-05-30 19 39 02](https://cloud.githubusercontent.com/assets/15164994/15657192/39986a12-269e-11e6-9e9d-176234aff526.png)
![screenshot from 2016-05-30 19 54 23](https://cloud.githubusercontent.com/assets/15164994/15657445/5888d482-26a0-11e6-8628-699cf362bd99.png)

**Comment by git-artes** [comment]
Hi, 
Thanks for the interest in the project. 
Now, regarding your questions. First, the examples we provide were tested with a USRP B100, whose sampling rate could be set at 8MS/s. You should make sure that this is the case with the N200 (typically, right at the beginning it will tell you in the standard output that the requested sampling rate was achieved or not). 
Second, spectrum looks good to me. 
Third, if the sampling rate is correctly set, and an ISDB-T signal is there, you should try to make a "peak" appear in the upper graph of the last picture you sent, by trying different values of guard interval and mode. If you understand spanish, you may read http://iie.fing.edu.uy/investigacion/grupos/artes/gr-isdbt/papers/estudio_propagacion.pdf (in particular take a look at Figure 4). 
Please let me know if you got it working. 
best

**Comment by eaiglesiasr** [comment]
Hi!
To start, I comment the following:
I've just  obtained the "peak" (I attached a image). I had a problem with sampling rate since USRP N200 has 100MS/s  of sampling rate and USRP B100 has 64MS/s., but when I probed "viewing_the_constellation" two cases happened when Interpolate parameter of ofdm_synchronization block was modified ( I attached two images). 
![screenshot from 2016-05-31 19 36 42](https://cloud.githubusercontent.com/assets/15164994/15688854/bbbe95c0-276b-11e6-877a-1bb597fed2ab.png)
INTERPOLATE=YES 
![screenshot from 2016-05-31 20 11 10](https://cloud.githubusercontent.com/assets/15164994/15688905/f88a6e48-276b-11e6-93d5-9f6a3577c31a.png)
INTERPOLATE=NO
![screenshot from 2016-05-31 20 11 25](https://cloud.githubusercontent.com/assets/15164994/15688925/11389294-276c-11e6-9ab2-f6a614ee4c02.png)

**Comment by git-artes** [comment]
That's weird. The difference between Interpolate yes and no, is whether to estimate and compensate for the sampling error. In any case, it should perform better. What sampling rate are you using now? Which parameters on the rational resampler?
best

**Comment by eaiglesiasr** [comment]
Yes, I checked some connections and found a problem with antenna, now I can receive well Interpolate yes and no (sampling rate and parameters can be checked in the attached image).
![sampraterational](https://cloud.githubusercontent.com/assets/15164994/15747875/327bb27c-28cc-11e6-8d41-9cda17616aa4.png)

 However, there's a problem  some seconds after running the file (two images are attached). 
 Could be published  your comments?
![screenshot from 2016-06-02 14 09 52](https://cloud.githubusercontent.com/assets/15164994/15748288/dc35a628-28cd-11e6-90b6-902aea37030d.png)
![screenshot from 2016-06-02 14 09 59](https://cloud.githubusercontent.com/assets/15164994/15748292/e151cd1c-28cd-11e6-9630-fc9c23aa9682.png)

**Comment by git-artes** [comment]
Hi, 
Glad it worked. Regarding the last problem, you are getting some "O"s, meaning your machine is not fast enough to process the whole flowgraph. Try enabling the Stream to Vector and Vector to Stream blocks and see if it works. 
best

**Comment by eaiglesiasr** [comment]
Hi,
I tried enabling the Stream to Vector and Vector to Stream blocks, using "Num Items" matches 2M,  and saw that continues the problem (I attached two pictures), is "Num Items" matches 2M  accuracy?  
![screenshot from 2016-06-03 16 16 00](https://cloud.githubusercontent.com/assets/15164994/15791967/ecc91702-29c9-11e6-9195-1f94ffe79db6.png)
![screenshot from 2016-06-03 16 16 10](https://cloud.githubusercontent.com/assets/15164994/15791972/f2c167ae-29c9-11e6-8bb3-6d12c0dfaa77.png)
Furthermore, I tried to check sampling error, but a message was displayed...
![screenshot from 2016-06-03 16 32 20](https://cloud.githubusercontent.com/assets/15164994/15792033/4f1a0696-29ca-11e6-8d5b-800965f0a535.png)
Is it OK the way to measure o there's any other way?

**Comment by git-artes** [comment]
Hi, 

The "stream to vector" -> "vector to stream" trick acts as a buffer, so eventually, if your machine is not fast enough, you will get overflows (as the "D"s indicate in the output). However, you have already obtained the parameters, and you should try using the rx_demo to check whether or not the system is able to decode the signal (obtaining_the_parameters.grc is very CPU intensive and not optimized at all). If not, you can always make a recording and see if it works. 

Now, regarding the last picture, you should read the error it reports: "Missing connection from output port 1". You should connect a null sink or something on the rest of the output ports to make it work. 

best
Federico

**Comment by git-artes** [comment]
I'm closing the issue since no further feedback was received.
