### ISSUE TITLE
Dongle DVB-t RTL2832+RT820t ISDBT 1seg

### ISSUE THREAD

**Issue by andregcoimbra** [git-artes/gr-isdbt#16]
Hi,

I have a dongle DVB-t rtl2832+rt820t and was atempted use with 1seg isdb-t project but not got any parameters. The dongle work well with FM and GSM reception. I need some special atention do make work?

Best Regards

**Comment by git-artes** [comment]
Hi, 
We'll be more than glad to help, but you should be more specific on the problem you're having. Did you got gnuradio installed? Did you got gr-isdbt compiled? Does gr-isdbt runs? Do you see the constellation? Do you have trouble obtaining a usable multimedia signal?
best
Federico

**Comment by andregcoimbra** [comment]
Hi, Frederico,

Since my question I really improved my tests. I have changed the blocks to work with my dongle and the result are this parameters but the results are inconstant. Follow the prints.
best.
Andre G. Coimbra

![screenshot from 2016-07-01 18-07-16](https://cloud.githubusercontent.com/assets/19873738/16535822/9c68543a-3fb8-11e6-8f0f-d41e7e722039.png)

 
![screenshot from 2016-07-01 18-23-41](https://cloud.githubusercontent.com/assets/19873738/16535861/18230aac-3fb9-11e6-8ff5-b133e3360e85.png)

**Comment by git-artes** [comment]
Hi, 
It looks like you got a really poor SNR. The correlation (in the first picture) should have a much more clear "peak", and you got what looks like the QPSK (what's normally transmitted in a 1-seg signal) but it's really noisy. Try a different antenna, or different position. 
You should also make sure to configure the rest of the blocks (time deinterleaver and viterbi decoder notably) accordingly (else, the Reed-Solomon decoder will deem the bytes incorrectable and not output anything, thus resulting in a file with 0 byte). 
best

**Comment by andregcoimbra** [comment]
Hi, Thanks a lot for your help. Glad your tip I had change the antenna and worked very well. Now I will enjoy the project. 
Best regards

![screenshot from 2016-07-02 14-32-25](https://cloud.githubusercontent.com/assets/19873738/16542982/a6b5fce2-408c-11e6-998e-cd92a634c8ee.png)

**Comment by git-artes** [comment]
Glad it worked. 
best
