### ISSUE TITLE
PARAMETERS MEASUREMENTS 

### ISSUE THREAD

**Issue by eaiglesiasr** [git-artes/gr-isdbt#17]
Hi Federico.
Sometime ago, I was working with fullseg_receiver_and_measurements.gcc in order to receive Transport Stream from local DTV channel  which achieved, I attached one image. 
![captura de pantalla de 2016-07-28 11-18-48](https://cloud.githubusercontent.com/assets/15164994/17218250/2c564cc6-54b5-11e6-9295-2861edde8767.png)

However, so far I haven´t been able to achieve good measurements of SNR, freq_error, and samp_error as same as figure 8 and 9 of "Efectos del canal sobre la señal de ISDB-T
Un caso de uso de gr-isdbt" paper. I attached two images.
![captura de pantalla de 2016-07-28 11-26-14](https://cloud.githubusercontent.com/assets/15164994/17218546/212080be-54b6-11e6-9d3b-3fa6c07fddb8.png)
![captura de pantalla de 2016-07-28 11-25-40](https://cloud.githubusercontent.com/assets/15164994/17218556/260627a0-54b6-11e6-80fd-5aebd70410f8.png)
Is it OK the way as I configured the before images? and 
Is it possible, Federico, that you can share  how I can configure in the good way the blocks to obtain SNR, freq_error, and samp_error, measurements,  please?

**Comment by git-artes** [comment]
Hi, 
What do you mean by "I haven´t been able to achieve good measurements of SNR, freq_error, and samp_error"? You are not obtaining good measurements, or do you believe the measurements that gr-isdbt (or gr-mer) is reporting are wrong? 
From the graphs you are showing (specially the last one), it looks like you are getting a very low signal (you should get a much more triangular "peak"). You should try getting either a new antenna or a better position. Note that our report was made with a line-of-sight. When indoors, we tend to use an antenna specifically for DTV, or else we get similar measurements as what you are showing. 
best
Federico

**Comment by eaiglesiasr** [comment]
Hi,
I mean by "I haven´t been able to achieve good measurements of SNR, freq_error, and samp_error" that  SNR measure, in particular, has been too unstable like it's possible to appreciate in the following figures:
![captura de pantalla de 2016-07-15 15-33-56](https://cloud.githubusercontent.com/assets/15164994/17223755/025b4b58-54cc-11e6-984b-311ed26e3b3f.png)
![captura de pantalla de 2016-07-28 13-52-44](https://cloud.githubusercontent.com/assets/15164994/17223765/0808cc7e-54cc-11e6-865d-4974b3e1d94e.png)
![captura de pantalla de 2016-07-28 13-52-39](https://cloud.githubusercontent.com/assets/15164994/17223769/0ddaf74e-54cc-11e6-90bb-0db77c88cefb.png)

**Comment by git-artes** [comment]
Hi, 
The SNR estimation is taken from the estimation of the symbol alignment (this is described in the original paper the synchro algorithm is based on [1]). In previous picture you've shown a very noisy correlation function, which will result in unstable symbol alignment estimations, and thus SNR estimations. 
For more details you should refer to the article [1], and take a look at the Sym Align Ofdm internals. 
best
Federico
[1] J.-J. van de Beek, M. Sandell, and P. Borjesson, “ML estimation of time and frequency offset in OFDM systems,” Signal Processing, IEEE Transactions on, vol. 45, no. 7, pp. 1800–1805, Jul 1997
