### ISSUE TITLE
Command to use ffplay on test_output.ts file

### ISSUE THREAD

**Issue by ergwd-pcieerd** [git-artes/gr-isdbt#25]
Hi,
I just need to know what actual command to use in playing test_output.ts file with ffplay? I never used ffmpeg and ffplay before and directly using `ffplay test_output.ts` doesn't show anything. Do I need to convert the file with ffmpeg to a .mp4 format, then use ffplay? Just got to ask as this might actually be a one liner you guys readily know...

Thanks a lot for attending to my newbie questions.

Cheers,
Daryl

**Comment by git-artes** [comment]
Hi, 
What's the size of the resulting test_output.ts? Because if it is 0 byte, it means the RS decoder is considering the stream beyond correction, typically meaning (if your constellation is "nice") that you are setting the parameters wrong (e..g time interleaver depth).
best

**Comment by ergwd-pcieerd** [comment]
I see... I got ffplay running by using one of your demo .dat files (569MHz_recording.dat). It's constellation and video playback is shown in the attached image. So for it to be accepted by the RS decoder, I guess my constellation will have to like something like it right?

![image](https://user-images.githubusercontent.com/43880366/47601874-1bc11680-da09-11e8-9841-67d0da03685b.png)

Will check test_out.ts on my own experiment. Will get back at this.

**Comment by ergwd-pcieerd** [comment]
Going back to my own experiment, and checking test_out.ts, it is 0 byte indeed. The constellation was also nothing like in above (image below).
![image](https://user-images.githubusercontent.com/43880366/47601973-78710100-da0a-11e8-9f8f-86f318a63488.png)

I'm attaching my flowgraph below, perhaps you can see which parameter I got wrong? I really appreciate you helping out on this.
![rx_demo grc](https://user-images.githubusercontent.com/43880366/47602004-e5849680-da0a-11e8-8368-9e8470f8f29d.png)

**Comment by ergwd-pcieerd** [comment]
Following up:

Is this the expected form of the obtaining parameters flowgraph?
![image](https://user-images.githubusercontent.com/43880366/47602181-78becb80-da0d-11e8-9d67-10a3f3099b73.png)

I now understand the instructions better...but, I will need to find the parameters that can give this kind of form. 

Thanks,
Daryl

**Comment by ergwd-pcieerd** [comment]
OK, thanks for confirming that...I will find those parameters - I'll get back at this on my next free time. You can close this issue now sir. as ffplay turned out fine when fed with correct isdbt data.
