### ISSUE TITLE
How i can use in Windows 10

### ISSUE THREAD

**Issue by nkhs** [git-artes/gr-isdbt#27]

**Comment by git-artes** [comment]
Hi, 
Our project depends on GNU Radio, which was designed for linux. There exists a working port to windows of GNU Radio, but our experience working with it is null, so we cannot help you. 
My personal recommendation is that it will be much easier to install an ubuntu (or similarly easy to install linux distro), GNU Radio and then our project, than trying to make it work under windows. 
best

**Comment by git-artes** [comment]
Hi, 
In case you are still interested, I've checked the new WSL and gr-isdbt works. 
best
