### ISSUE TITLE
rx_1seg_demo.grc testing

### ISSUE THREAD

**Issue by viamonte** [git-artes/gr-isdbt#44]
Hi, I'm trying to run the rx_1srg_demo on the non-tested 3.8 version of the gr-isdbt module, I'm actually not sure if I'm doing something wrong I just need some assistance on the topic.

Once I run the example gnuradio starts receiving a data stream and then it freezes (the terminal does keeps running), I'm kinda new on the topic so I don't know if that's supposed to happen, also I try running ffplay to see the converted data on a video stream but nothing is showing. 

Here's a piece of what the terminal is showing:

```

```
Error: failed to enable real-time scheduling.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya 
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_3.15.0.0-7-g8d228dbe
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 1015873.002204 Hz
[R82XX] PLL not locked!
Segments: 1
d_noutput: 384
gr::buffer::allocate_buffer: warning: tried to allocate
   348 items of size 188. Due to alignment requirements
   1024 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
gr::buffer::allocate_buffer: warning: tried to allocate
   321 items of size 204. Due to alignment requirements
   1024 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
gr::buffer::allocate_buffer: warning: tried to allocate
   321 items of size 204. Due to alignment requirements
   1024 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
previous_symbol: 0, 
 current_symbol: 3
d_corr_sp = {3.236742, 4.574428, 3.136580, 8.024161}
OFDM_SYNCHRO: peak at border! peak 0.000016, avg_max 0.000025, avg_min -0.009879, peak_index: 15
OFDM_SYNCHRO: peak at border! peak 0.000478, avg_max 0.000433, avg_min -0.008460, peak_index: 1022
VITERBI: d_init=True
OFDM_SYNCHRO: peak under/over average! peak -0.008831, avg_max 0.000474, avg_min -0.013260
OFDM_SYNCHRO: peak at border! peak -0.008831, avg_max 0.000474, avg_min -0.013260, peak_index: 15
previous_symbol: 0, 
 current_symbol: 3
d_corr_sp = {3.382313, 2.872745, 4.091533, 5.052872}
OFDM_SYNCHRO: peak under/over average! peak -0.008009, avg_max 0.000429, avg_min -0.009520
OFDM_SYNCHRO: peak at border! peak 0.000332, avg_max 0.000342, avg_min -0.010759, peak_index: 1023
previous_symbol: 3, 
 current_symbol: 3
d_corr_sp = {6.834692, 3.271213, 3.314949, 11.358335}
OFDM_SYNCHRO: peak at border! peak -0.000212, avg_max -0.000145, avg_min -0.011191, peak_index: 15
previous_symbol: 3, 
 current_symbol: 2
d_corr_sp = {2.373575, 3.242822, 6.079180, 2.500492}
OFDM_SYNCHRO: peak under/over average! peak -0.008780, avg_max 0.000663, avg_min -0.011252
previous_symbol: 2, 
 current_symbol: 0
d_corr_sp = {10.053485, 2.428819, 2.496308, 5.088914}
OFDM_SYNCHRO: peak under/over average! peak -0.007923, avg_max 0.000249, avg_min -0.011654
OFDM_SYNCHRO: peak at border! peak -0.007923, avg_max 0.000249, avg_min -0.011654, peak_index: 15
previous_symbol: 0, 
 current_symbol: 0
d_corr_sp = {7.159842, 6.194774, 2.898567, 3.581966}
OFDM_SYNCHRO: peak under/over average! peak -0.010274, avg_max 0.000373, avg_min -0.012451
OFDM_SYNCHRO: peak under/over average! peak -0.003635, avg_max 0.000373, avg_min -0.010749
OFDM_SYNCHRO: peak at border! peak -0.003635, avg_max 0.000373, avg_min -0.010749, peak_index: 1
previous_symbol: 0, 
 current_symbol: 2
d_corr_sp = {4.634711, 3.504941, 9.641738, 2.182652}
OFDM_SYNCHRO: peak under/over average! peak -0.009325, avg_max 0.000509, avg_min -0.011365
OFDM_SYNCHRO: peak at border! peak -0.009325, avg_max 0.000509, avg_min -0.011365, peak_index: 0
OFDM_SYNCHRO: peak under/over average! peak -0.009756, avg_max 0.000642, avg_min -0.008067
previous_symbol: 3, 
 current_symbol: 3

```

```
And then it goes of like that until it's killed. The picture is showing what I see on the gnuradio screen

![Captura de pantalla de 2020-06-18 17-08-13](https://user-images.githubusercontent.com/44510101/85072252-c362fd80-b186-11ea-95b9-311ab0276a2a.png)

**Comment by git-artes** [comment]
Hi. 
You should try running the demos with the provided recorded signals (see the files at https://iie.fing.edu.uy/investigacion/grupos/artes/projects/gr-isdbt/, there's one with a dongle recording). Once you've gotten familiar with that, you may try using the system with an over-the-air reception. However, note that you have to find the correct parameters first (i.e. the mode, CP, etc.). See the obtaining_the_parameters.grc flowgraph. 

In the project's website there are some documents in spanish that explain the whole process. 
best
