### ISSUE TITLE
Not compatible with gnuradio 3.8.2.0

### ISSUE THREAD

**Issue by ngammarano** [git-artes/gr-isdbt#45]
When doing
```
cmake ../
```

I get that it could not find a configuration file for package "Gnuradio" that is compatible with requested version "3.7.2" (since I have version 3.8.2.0 installed).

**Comment by git-artes** [comment]
Hi Nicolás, 
Right now, it's compatible with GNU Radio 3.7 only. You may use our docker for 3.7 to check it out: https://github.com/git-artes/docker-gnuradio/tree/master/gnuradio-releases-37. 
best

**Comment by ngammarano** [comment]
OK, thank you. I recommend making this clear in the README.

**Comment by git-artes** [comment]
Hi, 
Documentation is a great first pull request ;-)
Best
