### ISSUE TITLE
tx_demo.grc not work on mobile devices!

### ISSUE THREAD

**Issue by CassianoDev** [git-artes/gr-isdbt#47]
I've tried everything and I can't get a cell phone to play the channel, I've tested one segment / 12 segments and nothing, all types of transmission, changed: rate, guard, modulation and etc and not work.

When searching, the cell phone stops for a few seconds detecting the signal like a TV does, but it after seconds continues to search without playing the transmission...

All TVs played both the full segment and the single segment, but the cell phone doesn't.
They seem to recognize the signal but something strange happens that they don't ring!

Is flowchart:
![Gnu](https://user-images.githubusercontent.com/49691326/128390360-b8087a36-9ed5-496a-95d5-d45c203e4c68.png)

**Comment by git-artes** [comment]
Thanks for the interest in the project. We've tested our system in TVs only. We've had feedback from people trying to use it on PSP decoders that couldn't make it work, and it seems to be a video encoding issue. I'm sorry to be of little help, but without the actual hardware to test it I'm not sure we may do much more.

**Comment by CassianoDev** [comment]
> Thanks for the interest in the project. We've tested our system in TVs only. We've had feedback from people trying to use it on PSP decoders that couldn't make it work, and it seems to be a video encoding issue. I'm sorry to be of little help, but without the actual hardware to test it I'm not sure we may do much more.

Got it, I wanted it to work on the smartphone! :(
I don't know where to start to make it work.

**Comment by CassianoDev** [comment]
After last update to Gnuradio 3.8, smartphone work now! 
Thanks
