### ISSUE TITLE
Problem to play .ts file with ffplay

### ISSUE THREAD

**Issue by AudioStone** [git-artes/gr-isdbt#52]
Hey! I downloaded the .dat archive from your page "569MHz_dongle_recording.dat" . And when I try playing it with the command line
"ffplay 569MHz_dongle_recording.dat ", there is a warning about incompatible input, what am I doing wrong?´
Hope you can help me :(

**Comment by git-artes** [comment]
Hello, 
The recording are IQ samples, not the decoded video. It's supposed to be fed to the flowgraph.
best
