### ISSUE TITLE
Trouble with finding the correct parameters (HackRFOne)

### ISSUE THREAD

**Issue by AudioStone** [git-artes/gr-isdbt#54]
Hi, I've been reviewing your work on the ISDB-TB receiver and I'm having some problems playing the .ts file with ffplay. This is because I can't set the parameters right, to display a constellation similar to the one in the paper (I use a HackRfOne). Can you give me any suggestions please? I'm in Salta - Argentina. I know that the standard says that isdb works in Argentina in Mode 3 and guard interval=1/4. But I'm trying with different frequencies and can't find anything :(
I tried every mode and guard interval and i'm uneable to find a clear peak. 
![Foto1](https://user-images.githubusercontent.com/90868192/199843923-549c9a45-babb-477e-b9c7-28fe62f6f71e.png)
![foto2](https://user-images.githubusercontent.com/90868192/199844011-cbaa7f63-644f-47fb-900c-a66c01f478ba.png)
![foto3](https://user-images.githubusercontent.com/90868192/199847264-fe85e2eb-54f0-4d54-84fb-1053bdbc0380.png)

**Comment by git-artes** [comment]
hi, 
It seems like the mode is indeed 3, but you're not getting the guard interval right (the plateau in the autocorrelation graph is very big). 
On the other hand, what spectrum are you getting? Is the TV signal strong enough? I see you haven't changed the gain settings.

**Comment by AudioStone** [comment]
With the others guard intervals, it just get worse: 
![undieci](https://user-images.githubusercontent.com/90868192/199853001-9351810a-1933-43ae-9069-0eccecaba032.png)
![unoctavo](https://user-images.githubusercontent.com/90868192/199853006-226e8640-a908-4da5-b793-5035e3fd5659.png)
I'm getting this spectrum: 

![spectrum](https://user-images.githubusercontent.com/90868192/199853177-23f1880d-05c2-424d-9871-cfc5692c0347.png)
Should I modify the gain?

**Comment by git-artes** [comment]
That's clearly too little power you're getting from the signal. Try increasing the gains or getting closer to the antenna. Are you sure that's the correct frequency?

**Comment by AudioStone** [comment]
I´m not actually sure, i was trying with the following list of channels from Argentina: 
Canal 14: 473.143 MHz.
Canal 15: 479.143 MHz.
Canal 16: 485.143 MHz.
Canal 17: 491.143 MHz.
Canal 18: 497.143 MHz.
Canal 19: 503.143 MHz.
Canal 20: 509.143 MHz.
Canal 21: 515.143 MHz.
Canal 22: 521.143 MHz.
Canal 23: 527.143 MHz.
Canal 24: 533.143 MHz.
Canal 25: 539.143 MHz.
Canal 26: 545.143 MHz.
Canal 27: 551.143 MHz.
Canal 28: 557.143 MHz.
Canal 29: 563.143 MHz.
Canal 30: 569.143 MHz.
Canal 31: 575.143 MHz.
Canal 32: 581.143 MHz.
Canal 33: 587.143 MHz.
Canal 34: 593.143 MHz.
Canal 35: 599.143 MHz.
Canal 36: 605.143 MHz.
I will try increasing the gains, but how can I find the correct frequency faster? Is there a way to make a frequency sweep or something like that?

**Comment by git-artes** [comment]
You should try with gqrx or any other SDR software that let's you check the spectrum, and try to find a strong signal.
