### ISSUE TITLE
1-seg Reciever Example

### ISSUE THREAD

**Issue by dlflor** [git-artes/gr-isdbt#61]
Hello! Thank you for making your work avaiable for the sdr community!

I've successfully used the provided examples to decode a 13-segment signal and obtain two transport streams for each layer, using the 569 MHz recording test data from the group's site. However, I can't seem to decode or even obtain the TMCC parameters for the 1-seg signal (the dongle 569 Mhz recording with ~1MHz bandwidth). I can see the peaks in the OFDM time sync when I choose the correct mode and CP length, but the message "TMCC NOT OK" is displayed by the TMCC decoder.

Is there any additional configuration I can make in the rx_demo example to allow it to work for 1-seg signals? The README mentios a rx_1seg_demo.grc example, but it is not available in the current version of the repository.

**Comment by git-artes** [comment]
Hi, 
Sorry but I'm not sure that example didn't get ported to the newer branches and it's only on the maint-3.7 one. This next months I'll go over the code base since the semester is about to start and we use it in our course. Until then, you can simply download it form that branch.
best
