### ISSUE TITLE
uhd warning

### ISSUE THREAD

**Issue by kokoacebedo** [git-artes/gr-isdbt#9]
After successfully generating and running the different .ts(saeta) raw baseband signals, I've tried using the usrp source and proceed with the obtaining parameters grc file. The simulation had uhd warnings and even if I changed the values, they still re
![error](https://cloud.githubusercontent.com/assets/16590404/12666241/da515390-c679-11e5-8dbc-81b32251bb62.PNG)
appear

**Comment by git-artes** [comment]
Hello, 

Let me focus on the last three UHD Warnings. You are using a N210, which it seems (as the UHD is warning you) does not support 8MS/s. The sampling rate used in our examples is based on a B100, using the default 64MHz master clock (which results in a even decimation of 8). This is then followed by a rational resampler of 64/63, which results in the 512/63 MS/s required by the OFDM signal. 

I believe the master clock of the N210 is 100MS/s. You should look for a combination of USRP sampling rate and rational resampler that is both supported by the N210 and results in an even decimation, and moreover feeds the rest of the flowgraph with 512/63 MS/s. 

I don't know what the first three UHD Warnings mean. 

best
Federico
